# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'adopt'
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
            - name: Build with Gradle
              run: ./gradlew test jacocoTestReport
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                # token: ${{ secrets.CODECOV_TOKEN }}
                # files: ./**/build/reports/jacoco/test/jacocoTestReport.xml
                verbose: true

